fix bug the filtered notifications are recorded in the notification h…
kubesphere/notification-manager pull request #116
Opened 2022-01-05 09:33 UTC by wanjunlei

…istory

Signed-off-by: wanjunlei <wanjunlei@kubesphere.io>

2022-01-05 09:59 UTC, benjaminhuo commented on pkg/history/history.go
> +			if err != nil && len(err) > 0 {
Do we need to add a retry limit here?

2022-01-06 02:50 UTC, wanjunlei commented on pkg/history/history.go
> +			if err != nil && len(err) > 0 {
Done

2022-01-07 02:25 UTC, benjaminhuo requested changes

2022-01-07 02:56 UTC, wanjunlei commented on pkg/notify/notifier/email/email.go
> +		if err := n.notifierCfg.HistoryInQueue(newData); err != nil {
Deduplication is done by ES.

<img width="960" alt="1641524155(1)" src="https://user-images.githubusercontent.com/53003665/148484086-8357b710-7a28-4acd-9c34-5dfe2557a1b9.png">

2022-01-07 05:23 UTC, benjaminhuo approved these changes

2022-01-07 05:23 UTC, merged