update doc
kubesphere/notification-manager pull request #129
Opened 2022-04-11 08:41 UTC by wanjunlei

Signed-off-by: wanjunlei <wanjunlei@kubesphere.io>

2022-04-12 08:35 UTC, Bettygogo2021 reviewed
Hi, some issues are repetitive, so you can search all of them and batch modify them.
For any doubts, feel free to contact me.

2022-04-12 08:35 UTC, Bettygogo2021 commented on docs/crds/router.md
> +A router that route all notifications to the all receivers of tenant `user1`.
route>>>routes

2022-04-12 08:35 UTC, Bettygogo2021 commented on docs/crds/router.md
> +A router that route cluster-level notifications to the email receivers `user1`.
route>>>routes

2022-04-12 08:35 UTC, Bettygogo2021 commented on docs/crds/silence.md
> +A silence that mute all notifications in namespace `test` and activate at `2022-02-29T00:00:00Z` for 24 hours.
1. mute>>> mutes
2. activate >>> is activated

2022-04-12 08:35 UTC, Bettygogo2021 commented on docs/template.md
> +The notifications sent to receivers constructed via templates. The Notification Manager comes with default templates, but they can also customize.
sent >>> are sent
but they can also customize>>> which also support customization

2022-04-12 08:35 UTC, Bettygogo2021 commented on docs/template.md
> +The notification templates based on the [Go templating](https://pkg.go.dev/text/template) system.
based on >>> is based on

2022-04-12 08:35 UTC, Bettygogo2021 commented on docs/template.md
> +- `Status` returns the status of `Alerts`. if there has a firing alert in `Alerts`, it returns `firing`, else return `resolved`.
else return >>> else it returns

2022-04-12 08:35 UTC, Bettygogo2021 commented on docs/template.md
> +Notification manager supports custom the notification language.
custom the notification language>>>language customization

2022-04-12 08:35 UTC, Bettygogo2021 commented on docs/template.md
> +The `languagePack` is a list of `ConfigmapKeySelector`. The configmap likes this.
likes this: is like this.

2022-04-13 03:02 UTC, wanjunlei commented on docs/crds/notification-manager.md
> +# NotificationManager CRD
The `NotificationManager` is the name of CRD.

2022-04-15 09:28 UTC, benjaminhuo requested changes

2022-04-18 01:32 UTC, benjaminhuo approved these changes

2022-04-18 01:32 UTC, merged

2022-04-18 01:32 UTC, benjaminhuo commented
This is a huge improvement!