fix SMS provider huawei
kubesphere/notification-manager pull request #92
Opened 2021-07-28 07:52 UTC by zhu733756

Signed-off-by: zhu733756 <talonzhu@yunify.com>
- remove the field TemplateParas, the value of this field should be generated by the notification messages.
- fix a bug in the generation process of the request header.
- fix templateParas: add regex rules to extract the return values of alertname,alerttype,severity,message,summary

2021-07-28 07:54 UTC, zhu733756 commented
/cc @benjaminhuo @wanjunlei

2021-07-28 08:16 UTC, benjaminhuo requested changes

2021-07-28 08:16 UTC, benjaminhuo commented on pkg/notify/notifier/sms/huawei.go
> +func generateParas(messages string) []string {
generateParas =>  generateParams

2021-07-28 08:16 UTC, benjaminhuo commented on pkg/notify/notifier/sms/huawei.go
> +// i.e: Reviced notifications: alertname:${TEXT}, alerttype:${TEXT}, serverity:${TEXT}, message:${message}, summary:${summary}
Reviced => Received

2021-07-28 08:16 UTC, benjaminhuo commented on pkg/notify/notifier/sms/huawei.go
> +// Pls make your custem SMS template containing five placeholders, you can set the template on the console of SMS huawei cloud provider.
Pls make your custem SMS template containing five placeholders =>
Pls make your custom SMS template containing five placeholders

2021-07-28 08:16 UTC, benjaminhuo commented on pkg/notify/notifier/sms/huawei.go
> +// Pls make your custem SMS template containing five placeholders, you can set the template on the console of SMS huawei cloud provider.
you can set the template on the console of SMS huawei cloud provider. =>
you can create an SMS template in Huawei Cloud's SMS console.

2021-07-29 12:40 UTC, wanjunlei approved these changes

2021-07-29 15:00 UTC, benjaminhuo commented on README.md
> +[QingCloud Container platform alarm] alertname = ${TEXT}, alerttype = ${TEXT}, severity = ${TEXT}, message = ${TEXT}, summary = ${TEXT}
QingCloud Container platform alarm =>
KubeSphere alerts

2021-07-30 01:15 UTC, zhu733756 commented on README.md
> +[QingCloud Container platform alarm] alertname = ${TEXT}, alerttype = ${TEXT}, severity = ${TEXT}, message = ${TEXT}, summary = ${TEXT}
fixed

2021-07-30 06:34 UTC, benjaminhuo approved these changes

2021-07-30 06:34 UTC, merged